# -*- coding: utf-8 -*-
"""Guvi_assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VvMVGxcwuwOp-dbiMYgBCyg-tB08JGNi
"""

#Create a text file:
f = open("D:\\guviassignmnt1.txt", "a")

#Registration function:
def registration():
    #Create a email id for registration:
    while True:    
        user_name=input("Please enter a valid email id to create an account:  ")
        flag=0
        if user_name.count("@")!=1:
            flag=1
        if user_name.count(".")!=1:
            flag=1
        if user_name.index(".")-user_name.index("@") < 4:
            flag=1
        if user_name.index("@")<3:
            flag=1
        if user_name[-4:] != ".com":
            flag=1
        if user_name.index(".")<user_name.index("@"):
            flag=1
        if not user_name[0].isalpha():
            flag=1
        if flag==0:
            break

    #Create a password for the registration:
    while True:
        pswd=input("Please enter a valid password for registration:  ")
        flag1=0
        if len(pswd)<=5 or len(pswd)>=16:
            flag1=1
        if not any(not c.isalnum() for c in pswd):
            flag1=1
        if not any(c.isdigit() for c in pswd):
            flag1=1
        if not any(c.isupper() for c in pswd):
            flag1=1
        if not any(c.islower() for c in pswd):
            flag1=1
        if flag1==1:
            print("Password did not meet requirements! Enter again!! ")
        if flag1==0:
            break

    text_file = open("D:\\guviassignmnt1.txt","a")
    text_file.write(user_name+" "+pswd+"\n")
    text_file.close()


#Login function:
def login():
    usernamelist=[]
    passwordlist=[]
    file123=open("D:\\guviassignmnt1.txt","r")
    for line in file123:
        words=line.split()
        usernamelist.append(words[0])
        passwordlist.append(words[1])
    user_name=input("Enter your user name:  ")

    #invalid user name
    if user_name not in usernamelist:
        print("User name not found! Please create new account!")
    else:
        flag24=0
        while flag24!=1:
            password=input("Enter 1 to type your password or Enter 2 if you forgot password: ")
            #Forgot password
            if password=="2":
                while True:
                    retrieveornew=input("Enter 1 to retrieve the old password or Enter 2 to create a new password: ")
                    #Retrieve old password
                    if retrieveornew == "1":
                        print("Your password is:  "+passwordlist[usernamelist.index(user_name)])
                        flag24=1
                        break
                    #Create a new password
                    elif retrieveornew =='2':
                        while True:
                            newpswd=input("Please enter a new valid password: ")
                            flag1=0
                            if len(newpswd)<=5 or len(newpswd)>=16:
                                flag1=1
                            if not any(not c.isalnum() for c in newpswd):
                                flag1=1
                            if not any(c.isdigit() for c in newpswd):
                                flag1=1
                            if not any(c.isupper() for c in newpswd):
                                flag1=1
                            if not any(c.islower() for c in newpswd):
                                flag1=1
                            if flag1==1:
                                print("Password did not meet requirements! Enter again!! ")
                            if flag1==0:
                                break
                        passwordlist[usernamelist.index(user_name)] = newpswd
                        print("The password has been updated!!")
                        #print(passwordlist)
                        file1234=open("D:\\guviassignmnt1.txt","r")
                    
                        for line in file1234:
                            words=line.split()
                            #print(words)
                            if words[0] == user_name:
                                oldpswd=words[1]
                    
                        with open('D:\\guviassignmnt1.txt', 'r') as file :
                            filedata = file.read()
                        filedata = filedata.replace(oldpswd, newpswd)
                        with open('D:\\guviassignmnt1.txt', 'w') as file:
                            file.write(filedata)
                        #print(passwordlist)
                        flag24=1
                        break
                    else:
                        print("Invalid response! Please type again!")  
            #Type the password         
            elif password=="1":
                flag123=0
                while flag123!=1:
                    paswrd=input("Enter your password to login or Enter 'exit' to exit:  ")
                    file1234=open("D:\\guviassignmnt1.txt","r")    
                    for line in file1234:
                        words=line.split()
                        #print(words)
                        if words[0] == user_name:
                            if paswrd==words[1]:
                                print("Login successfull!!")
                                flag123=1
                            elif paswrd=="exit" :
                                flag123=1
                                break 
                            else:
                                print("Incorrect password!!")
                                
                break         
            else:
                print("Invalid response!")

#Main code
while True:
    user_data=input("Enter 1 to Login to existing account or Enter 2 to create a new account or Enter 3 to end the current session: ")
    #Registration:
    if user_data=="2":
        registration()
        print("Account created successfully!!")
        continue
    #Login    
    if user_data=="1":
        login()
        continue
    #Go back:
    if user_data =="3":
        print("Thankyou! Have a nice day!!")
        break
    #All other responses!
    else:
        print("Sorry invalid response!!")

f = open("D:\\guviassignmnt1.txt", "r")
print(f.read())